---
- name: Install X11 tools
  apt:
    state: present
    pkg:
    - i3
    - rofi
    - redshift
    - compton
    - dunst
    - feh
    - scrot
    - keynav
    - xdotool
  become: yes

- name: Getting dependencies to compile i3-gaps
  apt:
    state: present
    pkg:
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - xcb
    - libxcb1-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libev-dev
    - libxcb-xkb-dev
    - libxcb-cursor-dev
    - libxkbcommon-dev
    - libxcb-xinerama0-dev
    - libxkbcommon-x11-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libxcb-xrm0
    - libxcb-xrm-dev
  become: yes
  tags: gaps

- name: Cloning i3-gaps
  git:
    repo: https://www.github.com/Airblader/i3
    dest: "{{ bin_directory }}/i3-gaps"
  notify: Build i3-gaps

